Develop
baby-platom/loyalty-system pull request #1
Opened 2023-08-28 10:16 UTC by baby-platom

2023-08-30 20:18 UTC, valentinsoe requested changes
Спасибо за работу.

Многие замечание написал по коду, дополнительно к ним - в проекте нет тестов.
Схема с загрузкой статусов заказа из внешнего сервиса on-demand при малейшей нагрузке нежизнеспособна. Подразумевается что у нас есть фоновый процесс обновления статусов.

Стоит также подумать о то, чтобы вынести бизнес-логику из кода хендлеров.
Унести вспомогательные фкнции в отдельные пакеты(например проверку луна).

2023-08-30 20:18 UTC, valentinsoe commented on cmd/gophermart/main.go
> +	if err := server.Run(); err != nil {
Стоит добавить обработку сигналов для корректного завершения приложения

2023-08-30 20:18 UTC, valentinsoe commented on cmd/gophermart/main.go
> +	if config.Config.Local {
Рекомендую унести это в отдельный бинарный файл. И запускать его при локальном тестировании.
Не надо этот код иметь в "основной" части проекта.

2023-08-30 20:18 UTC, valentinsoe commented on internal/accrual/check.go
> +		logger.Log.Info("too many requests to accrual service")
Стоит добавить логику обработки этой ошибки(не отправлять запросы некоторое время)

2023-08-30 20:18 UTC, valentinsoe commented on internal/accrual/check.go
> +		return
Крайне неочевидно что именно в этом случае вернется. Пустая структура результата и пустая ошибка

2023-08-30 20:18 UTC, valentinsoe commented on internal/accrual/update.go
> +			go updateOrderCopy(i, orderCopy, orders[i], &ordersCopy, &changed, &wg)
Делить память(массив заказов) между горутинами - очень плохая практика.
Для передачи данных между горутинами стоит использовать каналы. В данном случае - возвращать результат стоит каналами.

2023-08-30 20:18 UTC, valentinsoe commented on internal/accrual/update.go
> +func updateOrderCopy(i int, orderCopy database.Order, order database.Order, ordersCopy *[]database.Order, changed *bool, wg *sync.WaitGroup) {
orderCopy может быть локальной переменной. Нет нужды ее сюда передавать.

2023-08-30 20:18 UTC, valentinsoe commented on internal/accrual/update.go
> +		return
Предлагаю ошибки хотя бы в лог зафиксировать

2023-08-30 20:18 UTC, valentinsoe commented on internal/accrual/update.go
> +			go updateOrderCopy(i, orderCopy, orders[i], &ordersCopy, &changed, &wg)
В целом кажется достаточно вызывать функцию updateOrderCopy с двумя параметрами:
1) orders[i]
2) канал для ответа

2023-08-30 20:18 UTC, valentinsoe commented on internal/auth/middleware.go
> +const UserLogin key = 0
Предлагаю дать ключу в контексте нормальное имя.
Если появится еще какая-то мидлвара и тоже ключом назначит 0?

2023-08-30 20:18 UTC, valentinsoe commented on internal/auth/middleware.go
> +// Middleware for compression and decompression
Кажется эта мидлвара не для сжатия

2023-08-30 20:18 UTC, valentinsoe commented on internal/compress/midleware.go
> +// Middleware for compression and decompression
А эта мидлвара только для сжатия.

2023-08-30 20:18 UTC, valentinsoe commented on internal/compress/midleware.go
> +var ContentTypesToBeEncoded = []string{"application/json", "text/html"}
Тоже остатки копипаста:)

2023-08-30 20:18 UTC, valentinsoe commented on internal/config/parse.go
> +func ParseFlags() {
Название и комментарий к функции не соответсвуют ее содержимому. Мы же не только флаги парсим.

2023-08-30 20:18 UTC, valentinsoe commented on internal/database/main.go
Название файла немного режет глаз.
init, db подошли бы лучше

2023-08-30 20:18 UTC, valentinsoe commented on internal/database/models.go
> +	CustomBaseModel
Если у нас у пользователя есть ID и именно по нему привязаны заказы(и это хорошее решение), то почему в токене у нас логин? Нам так постоянно придется из логина получать ID делая лишнее обращение в БД.

2023-08-30 20:18 UTC, valentinsoe commented on internal/server/auth.go
> +	if msg := checkIfOneStrcutFieldIsEmpty(*userData); msg != "" {
strcut -> struct

2023-08-30 20:18 UTC, valentinsoe commented on internal/server/auth.go
> +	if msg := checkIfOneStrcutFieldIsEmpty(*userData); msg != "" {
И вообще сложноватая функция, которая используется дважды. Кажется проще проверить поля "руками".

2023-08-30 20:18 UTC, valentinsoe commented on internal/server/auth.go
> +func parseUserData(w http.ResponseWriter, r *http.Request, userData *userDataStruct) bool {
Не надо передавать сюда указатель на userDataStruct. Лучше вернуть ее в ответе(и без указателя)

2023-08-30 20:18 UTC, valentinsoe commented on internal/server/orders.go
> +		defaultReactionToInternalServerError(w, logger.Log, err)
Так как проверки и добавление заказа сделаны не в рамках транзакций, у пользователя есть шанс получить 500 вместо 200 или 409

2023-08-30 20:18 UTC, valentinsoe commented on internal/server/utils.go
> +func Luhn(number string) bool {
CheckLuhn было бы лучше.

2023-08-30 20:18 UTC, valentinsoe commented on internal/server/orders.go
> +	orders, status, err := updateOrdersAccrual(r, user.ID, logger.Log)
Обновлять статус заказов под запрос не самая лучшая идея.
Во-первых это делает запрос пользователя медленным, если внешний сервис работает медленно. 
Во-вторых мы не фильтруем в дальнейших функциях, какие заказы мы хотим обновить, а проверяем все(даже те, что уже в финишных статусах)
Во-третьих даже если исправить во-вторых, 1000 одновременно запущенных запросов одного пользователя на получение списка заказов приведут к 1000*количество заказов запросов во внешнюю систему.

2023-08-30 20:18 UTC, valentinsoe commented on internal/server/utils.go
> +func calculateBalance(userID uint, orders []database.Order) (balance Balance, err error) {
Если нам нужно вернуть пользователю только баланс, то скачивать из БД все заказы и списания в приложение и обсчитывать это на нем очень неэффективно.

2023-09-03 08:44 UTC, baby-platom commented on internal/server/auth.go
> +	if msg := checkIfOneStrcutFieldIsEmpty(*userData); msg != "" {
мне проще воспринимать когда есть одна универсальная функция которая проверяет + в реальном проекте где уже было бы больше чем 2 раза, очень пригодилось бы

2023-09-04 08:21 UTC, baby-platom commented
Кроме правок, перенес часто юзаемые функции в отдельные пакеты. Но некоторые большие которые сильно связаны с хендлерами оставил рядом с хендлерами, т к иначе теряется пониманием.

Мне кажется доскональное разбиение на пакеты и разнос бизнес логики по кусочкам излишен, Avoid Premature Optimization.

У меня по опыту так что если вижу что стоит сделать сразу более гибко, разбить на функции и т п, то делаю. А в таком сервисе будто излишне сильно разносить 

И тесты  позже напишу, не успеваю)

2023-09-05 20:26 UTC, valentinsoe requested changes
Спасибо за исправления.

Текущий подход к фоновой обработке статусов заказов очень не эффективен и при этом сложно написан.

Написал также рекомендацию по транзакциям.
Более подробно можно тут например почитать: https://www.kaznacheev.me/posts/en/clean-transactions-in-hexagon/

2023-09-05 20:26 UTC, valentinsoe commented on internal/accrual/update.go
> +		outChan := getUpdatedOrder(cancelCh, order)
Зачем нам на каждый заказ создавать по каналу? Что нам это дает?

2023-09-05 20:26 UTC, valentinsoe commented on internal/accrual/update.go
> +	tx, err := database.GetTransaction()
Не самый удачный способ пронести транзакции в бизнес-логику.
Можно сделать на уровне БД функцию вида WithinTransaction(ctx context.Context, tFunc func(ctx context.Context) error) error { } и поддержать получение транзакции из контекста.

2023-09-05 20:26 UTC, valentinsoe commented on internal/accrual/update.go
> +		outChan := getUpdatedOrder(cancelCh, order)
В таком подходе мы создаем очень много(потенциально бесконечно) горутин и каналов.
Которые после этого все ждут одну горутину. Это очень неэффективно будет использовать ресурсы.

2023-09-05 20:30 UTC, valentinsoe commented
> Мне кажется доскональное разбиение на пакеты и разнос бизнес логики по кусочкам излишен, Avoid Premature Optimization.
> 
> У меня по опыту так что если вижу что стоит сделать сразу более гибко, разбить на функции и т п, то делаю. А в таком сервисе будто излишне сильно разносить

Это не Premature Optimization, это нарушения single responsibility principle. Это делает код сильно более читаемым и тестируемым. Ответственность хендлеров - читать и формировать http-запросы, более ничего.
В целом же можно вообще весь код проекта написать в одном файле и будет работать. Но я такую работу отправлю на переделку даже не читая:)

2023-09-06 05:32 UTC, baby-platom commented
> Написал также рекомендацию по транзакциям. Более подробно можно тут например почитать: https://www.kaznacheev.me/posts/en/clean-transactions-in-hexagon/

а я это почти сделал до этого, но выпилил т к был лишь один кейс использования транзакций и думал лишнее)

2023-09-06 08:10 UTC, baby-platom commented
Вынес всю логику работы с бд в database. В хэнделрах осталась роль точки где все сходиться

2023-09-07 03:20 UTC, valentinsoe approved these changes
Спасибо за исправления!

Я оставил один комментарий. Его лучше исправить перед мерджом.

2023-09-07 03:20 UTC, valentinsoe commented on internal/accrual/background.go
> +		if err := database.DB.WithinTransaction(ctx, UpdateOrders); err != nil {
Вот здесь как раз то место, где транзакция - лишняя.

2023-09-07 03:20 UTC, valentinsoe commented on internal/accrual/background.go
> +		if err := database.DB.WithinTransaction(ctx, UpdateOrders); err != nil {
С точки зрения того, что ждать в транзакции в БД выполнения HTTP-запросов точно не стоит.

2023-09-07 04:47 UTC, merged